# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

---
title: WeBuildThis.City
timezone: America/Chicago
locale: en
collections:
  content:
    title: Content
    output: true
    permalink: "/:path/"
  departments:
    title: Departments
    output: false
  glossary:
    title: Glossary
    output: false
  projects:
    title: Projects
    output: true
  icons:
    title: icons
    output: true
    permalink: "/assets/images/:collection/:path"

defaults:
- scope:
    path: ''
  values:
    layout: 'default'
- scope:
    path: ''
    type: icons
  values:
    layout: svg
- scope:
    path: ''
    type: 'projects'
  values:
    layout: 'project'
- scope:
    path: '_content/resources'
    type: 'content'
  values:
    layout: 'default'
    in_resources_menu: false
    in_permit_check_menu: false
- scope:
    path: 'assets'
  values:
    layout: false

_comments:
  department_name: The department's official name
  department_link: The link to the department's page on AustinTexas.gov
  phone: Please use the format 000-000-0000
  email:
  period_name: e.g., "General questions" or "By appointment only"
  period_time_markdown: Open-Close days and times, new lines OK
  physical_address_markdown: Actual address for visitors, new lines OK

description: The City of Austin’s Residential Permitting Resource
subtitle: Austin’s Residential Permitting Resource
show_full_navigation: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
gems:
  - jekyll-feed

# We specify the directory for Jekyll so we can use @imports.
sass:
  load_paths:
    - css
    - assets/css
    - neat
    - bourbon

permalink: pretty
exclude:
  - /node_modules/
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - npm-debug.log
  - /css
  - /screenshots
  - /sketch-files
  - ".ruby-version"
  - ".sass-cache"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - config
  - js
  - vendor
  - manifest.yml
  - node_modules
  - package.json
  - circle.yml
